### ISSUE TITLE
Fail to build locally

### ISSUE THREAD

**Issue by ulysses4ever** [PurduePL/purduepl.github.io#138]
Running the command from the readme:
```
❯ docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:3.8 jekyll serve --incremental --drafts --config _config.ym
Unable to find image 'jekyll/jekyll:3.8' locally
3.8: Pulling from jekyll/jekyll
9d48c3bd43c5: Pull complete 
9ce9598067e7: Pull complete 
278f4c997324: Pull complete 
bfca09e5fd9a: Pull complete 
2612f15b9d22: Pull complete 
322c093d5418: Pull complete 
Digest: sha256:9521c8aae4739fcbc7137ead19f91841b833d671542f13e91ca40280e88d6e34
Status: Downloaded newer image for jekyll/jekyll:3.8
Fetching gem metadata from https://rubygems.org/.........
nokogiri-1.15.4-x86_64-linux requires ruby version >= 2.7, < 3.3.dev, which is incompatible with the
current version, ruby 2.6.3p62
```

My OS is NixOS Unstable if it matters. I wonder if I'm the only one who's having this...

`jekyll:3.8` appears to be quite old (4 years), so I tried Jekyll 4, which moved further:

```
❯ docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:4 jekyll serve --incremental --drafts --config _config.ym
Unable to find image 'jekyll/jekyll:4' locally
4: Pulling from jekyll/jekyll
df9b9388f04a: Pull complete 
837e9cfc7e43: Pull complete 
c7850f1a8c23: Pull complete 
6ca4c39baa3d: Pull complete 
daa3a8cb79d3: Pull complete 
cf5821b9dd48: Pull complete 
Digest: sha256:400b8d1569f118bca8a3a09a25f32803b00a55d1ea241feaf5f904d66ca9c625
Status: Downloaded newer image for jekyll/jekyll:4
Bundler 2.3.25 is running, but your lockfile was generated with 2.0.2. Installing Bundler 2.0.2 and restarting using that version.
Fetching gem metadata from https://rubygems.org/....
...
Bundle complete! 3 Gemfile dependencies, 91 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-linux-musl]
           WARNING: Error reading configuration. Using defaults (and options).
            Source: /srv/jekyll
       Destination: /srv/jekyll/_site
 Incremental build: enabled
      Generating... 
                    done in 0.302 seconds.
 Auto-regeneration: enabled for '/srv/jekyll'
/usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:184:in `require_relative'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:184:in `setup'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:102:in `process'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `block in start'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `each'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:93:in `start'
        from /usr/gem/gems/jekyll-3.9.3/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
        from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
        from /usr/gem/gems/jekyll-3.9.3/exe/jekyll:15:in `<top (required)>'
        from /usr/local/bundle/bin/jekyll:29:in `load'
        from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

Google says this can be fixed with:
```
❯ docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 -it jekyll/jekyll:4 bundle add webrick
```

~~After that, the suggested command worked fine, albeit with a warning...~~  scratch that: the `--config` was my bad.

---

If anyone can reproduce the problem, perhaps we should:

- update README to suggest using Jekyll 4
- update the gemfile by adding `webrick` to it

**Comment by Pat-Lafon** [comment]
Usually you get incompatible versions because of the lock file. I sometimes solve this by removing the lock file and letting it reconstruct a new compliant one.

**Comment by ulysses4ever** [comment]
Indeed, that worked. It's baffling to me how the concept of a lock file can be implemented so poorly...

This is worth mentioning in README under a new section, like "Tips and Tricks" or some such.
